flags:
    miso:
        jsaddle: true
        examples: true
    # hgeometry:
    #     examples: true
    #     interactive: false
packages:
- '.'
- 'jsaddle/jsaddle-warp'
- '../hgeometry'
extra-deps:
- jsaddle-0.9.5.0
- jsaddle-dom-0.9.2.0
- ref-tf-0.4.0.1
- miso-0.21.2.0
allow-newer: true
build:
  # library-profiling: true
  # executable-profiling: true
extra-lib-dirs:
- /usr/lib
#resolver: lts-10.3
resolver: nightly-2018-05-25
